version: '3.8'

services:
  frontend:
<<<<<<< HEAD
    image: solydus/frontending:v1.02.2023
=======
    image: solydus/frontending:latest
>>>>>>> 282535e1136e115284fe0b1962dbb830000c0fff
    volumes:
      - ./frontend/build:/usr/share/nginx/html/

  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - database_data:/var/lib/postgresql/data/
    env_file: ./.env

  backend:
<<<<<<< HEAD
    build:
      context: .
      dockerfile: ./foodgram/Dockerfile
=======
    image: solydus/backend:latest
    #build: ../foodgram
>>>>>>> 282535e1136e115284fe0b1962dbb830000c0fff
    restart: always
    command: gunicorn foodgram.wsgi:application --bind 0.0.0.0:8000 --workers 4
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file: ./.env

  nginx:
    image: nginx:1.21.0-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_value:/var/www/static/
      - media_value:/var/www/media/
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs:/usr/share/nginx/html/api/docs/:ro
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "--retry-connrefused", "http://localhost/healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  static_value:
  media_value:
  database_data:
